### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by nicolasparada** [ndugger/blackbeard#2]
In nodejs is more common to see mongo as the database.
Maybe change sequelize by waterline, caminte or osmos (<-rethinkdb support).

**Comment by ndugger** [comment]
There's been a trend lately that more and more people are moving towards relational databases vs NoSQL; If more people request NoSQL support, I'll support it, but for now, I'm going to stick with Sequelize.

**Comment by nicolasparada** [comment]
Yeah, but libraries like the above mentioned does support sql databases besides nosql.
There is a lot of people using mongo.
Rethinkdb is a good database by the day too.

**Comment by ndugger** [comment]
Aye, but I'd probably have to rewrite my Model wrapper, and since many people do still use relational databases, there's not a huge demand for me to support NoSQL yet. However, like I said, if more people request it, I will definitely put in the work to switch out the ORM.
